name: Machine Learning Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-ci-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Environment Info
      run: |
        python --version
        pip --version

    - name: Install Base Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn

    - name: Run MLflow Project Execution
      run: |
        # Menjalankan proyek MLflow menggunakan direktori lokal pembungkus
        mlflow run MLProject/ --no-conda