name: Machine Learning Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-ci-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn

    - name: Execute Model Training
      run: |
          # Menjalankan re-training menggunakan standarisasi MLflow Project
          mlflow run MLProject --env-manager=local