name: Machine Learning Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-ci-run:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn

    - name: Run MLflow Project Execution
      run: |
        # Masuk dulu ke foldernya, baru jalankan MLflow di titik lokal (.)
        cd MLProject
        mlflow run . --env-manager=local